remote_theme: just-the-docs/just-the-docs
logo: "/assets/images/appIcon_2x.png"
search_enabled: true
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
