name: Release to Splunkbase
on: workflow_dispatch 

jobs:
   publish:
      runs-on: ubuntu-latest
      steps:
         - uses: diogofgm/splunkbase-release-action/.github/workflows/splunkbase-release-action.yml@v0.0.3
           with:
             SPLUNKBASE_USER: ${{ secrets.SPLUNKBASE_USER }}
             SPLUNKBASE_PASSWORD: ${{ secrets.SPLUNKBASE_PASSWORD }}
