name: Release to Splunkbase
on: workflow_dispatch 

jobs:
   publish:
      name: Publish to Splunkbase
      uses: diogofgm/splunkbase-release-action/.github/workflows/splunkbase-release-action.yml@v0.0.2
