name: Release to Splunkbase
on: workflow_dispatch 

jobs:
   publish:
      runs-on: ubuntu-latest
      name: Publish to Splunkbase
      steps:
         - uses: diogofgm/splunkbase-release-action@v0.0.3
           with:
               SPLUNKBASE_USER: ${{ secrets.SPLUNKBASE_USER }}
               SPLUNKBASE_PASSWORD: ${{ secrets.SPLUNKBASE_PASSWORD }}
