name: Release to Splunkbase
on:
  push:
    branches:
      - "main"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - ".github/**"
      - "docs/**"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
      - "docs/**"

jobs:
   build:
     uses: diogofgm/splunkbase-release-action/.github/workflows/splunkbase-release-action.yml@v0.0.1
