name: Release to Splunkbase
on: workflow_dispatch 

jobs:
   build:
     uses: diogofgm/splunkbase-release-action/.github/workflows/splunkbase-release-action.yml@v0.0.2
     with:
      SPLUNKBASE_USER: ${{ secrets.SPLUNKBASE_USER }} 
      SPLUNKBASE_PASSWORD: ${{ secrets.SPLUNKBASE_PASSWORD }} 
